name: CWP Docker Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  
jobs:
  # Jobs are ran independently from each other, so build and scan needs to be in a single job.
  scan-images:
    name: Scan image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        # Defaults are sufficient generally
        # https://github.com/actions/checkout#usage

      - name: Download twistcli from the Prisma Cloud Compute Console
        run: |
          curl --user ${{ secrets.PCC_USER }}:${{ secrets.PCC_PASS }} --output ./twistcli ${{ secrets.PCC_CONSOLE_URL }}/api/v1/util/twistcli
          chmod a+x ./twistcli

      - name: Pull Docker Image
        id: store_image_id
        run: | 
          docker pull vulnerables/web-dvwa
          pulled_image_id=$(docker image ls -q vulnerables/web-dvwa)
          echo "::set-output name=IMAGE_ID::$pulled_image_id"
          

      - name: Scan the image
        run: ./twistcli images scan --address ${{ secrets.PCC_CONSOLE_URL }} --user $${{ secrets.PCC_USER }} --password ${{ secrets.PCC_PASS }} --details ${{ steps.store_image_id.outputs.IMAGE_ID }}
